# ============================================================
# knowledge_base.py – CyberGuard Advisor
# 80 production rules across 5 cybersecurity domains.
#
# KNOWLEDGE ACQUISITION SOURCES:
#   - OWASP Top 10 (2023)
#   - NIST SP 800-63B
#   - Anti-Phishing Working Group (APWG) eCrime Reports
#   - FTC Consumer Sentinel Network
#   - CIS Controls v8 / SANS Security Awareness
#   - FBI IC3 Internet Crime Reports
#
# RULE STRUCTURE:
#   id         : Unique identifier (R01–R80)
#   desc       : Human-readable description
#   category   : password | url | phishing | scam | hygiene
#   conditions : ALL must be True (AND logic)
#   conclusion : Fact added to working memory
#   severity   : CRITICAL | HIGH | MEDIUM | LOW
#   confidence : Certainty Factor 0–100 (MYCIN-style)
#   rationale  : Knowledge acquisition justification
# ============================================================

RULES = [

    # ══════════════════════════════════════════════════════
    # PASSWORD SECURITY  R01–R18
    # ══════════════════════════════════════════════════════
    {"id":"R01","desc":"Very short password with no special characters",
     "category":"password","conditions":["pwd_length_very_short","no_special_char"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"NIST 800-63B: passwords under 6 chars with no complexity have near-zero entropy."},
    {"id":"R02","desc":"Short password with no digits",
     "category":"password","conditions":["pwd_length_short","no_digit"],
     "conclusion":"password_risk_high","severity":"HIGH","confidence":90,
     "rationale":"OWASP: minimum 8 chars required; absence of digits reduces entropy further."},
    {"id":"R03","desc":"No uppercase and no special characters",
     "category":"password","conditions":["no_uppercase","no_special_char"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":72,
     "rationale":"Mixed-case plus symbols increase keyspace exponentially per NIST guidance."},
    {"id":"R04","desc":"No digits and no uppercase letters",
     "category":"password","conditions":["no_digit","no_uppercase"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":70,
     "rationale":"All-lowercase alphabetic passwords are vulnerable to dictionary attacks."},
    {"id":"R05","desc":"No special characters and no uppercase",
     "category":"password","conditions":["no_special_char","no_uppercase"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":72,
     "rationale":"Passwords without symbols and mixed case fail OWASP ASVS Level 1."},
    {"id":"R06","desc":"Password is a known common or dictionary word",
     "category":"password","conditions":["common_password","no_special_char"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":97,
     "rationale":"NIST 800-63B: must check against breached password lists (HaveIBeenPwned)."},
    {"id":"R07","desc":"Password consists entirely of digits",
     "category":"password","conditions":["only_digits","no_special_char"],
     "conclusion":"password_risk_high","severity":"HIGH","confidence":88,
     "rationale":"Numeric-only passwords are brute-forced in seconds on modern hardware."},
    {"id":"R08","desc":"Password contains username and has no special characters",
     "category":"password","conditions":["contains_username","no_special_char"],
     "conclusion":"password_risk_high","severity":"HIGH","confidence":85,
     "rationale":"OWASP: passwords containing account identifiers are trivially guessable."},
    {"id":"R09","desc":"All-lowercase with no digits or special characters",
     "category":"password","conditions":["no_uppercase","no_digit","no_special_char"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"All-lowercase passwords with no complexity have the lowest entropy class."},
    {"id":"R10","desc":"Sequential characters with no special characters",
     "category":"password","conditions":["sequential_chars","no_special_char"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":75,
     "rationale":"Sequential patterns are among the first tried in credential stuffing attacks."},
    {"id":"R11","desc":"Repeated characters with no uppercase",
     "category":"password","conditions":["repeated_chars","no_uppercase"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":68,
     "rationale":"Repeated chars reduce effective entropy flagged by NIST password tools."},
    {"id":"R12","desc":"Strong password: long, mixed case, digits and specials",
     "category":"password","conditions":["pwd_length_strong","has_uppercase","has_digit","has_special_char"],
     "conclusion":"password_risk_low","severity":"LOW","confidence":92,
     "rationale":"NIST 800-63B: passwords 12+ chars with full complexity meet highest assurance."},
    {"id":"R13","desc":"Medium password: 8-12 chars with uppercase and digits",
     "category":"password","conditions":["pwd_length_medium","has_uppercase","has_digit"],
     "conclusion":"password_risk_low","severity":"LOW","confidence":78,
     "rationale":"Meets OWASP minimum but lacks special chars for full compliance."},
    {"id":"R14","desc":"Keyboard walk pattern with no special characters",
     "category":"password","conditions":["keyboard_pattern","no_special_char"],
     "conclusion":"password_risk_high","severity":"HIGH","confidence":86,
     "rationale":"Keyboard patterns are explicitly blacklisted in NIST SP 800-63B appendix."},
    {"id":"R15","desc":"Birth year pattern with no special characters",
     "category":"password","conditions":["contains_year","no_special_char"],
     "conclusion":"password_risk_medium","severity":"MEDIUM","confidence":73,
     "rationale":"Year patterns are predictable personal info per OWASP guidance."},
    {"id":"R16","desc":"Very short password with no digits",
     "category":"password","conditions":["pwd_length_very_short","no_digit"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":93,
     "rationale":"Length and digit absence combine for maximum vulnerability per NIST entropy model."},
    {"id":"R17","desc":"Common password that is also numeric-only",
     "category":"password","conditions":["common_password","only_digits"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":99,
     "rationale":"Top breached passwords (123456, 000000) are numeric-only common words."},
    {"id":"R18","desc":"Keyboard pattern combined with sequential characters",
     "category":"password","conditions":["keyboard_pattern","sequential_chars"],
     "conclusion":"password_risk_critical","severity":"CRITICAL","confidence":94,
     "rationale":"Two predictability patterns combined create near-zero unpredictability."},

    # ══════════════════════════════════════════════════════
    # URL SAFETY  R19–R34
    # ══════════════════════════════════════════════════════
    {"id":"R19","desc":"HTTP URL with suspicious keywords — unencrypted phishing",
     "category":"url","conditions":["url_http","url_suspicious_keywords"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":80,
     "rationale":"HTTP traffic is interceptable; combination with phishing keywords is high risk."},
    {"id":"R20","desc":"IP address URL over HTTP",
     "category":"url","conditions":["url_has_ip","url_http"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":90,
     "rationale":"APWG: 94% of phishing URLs using raw IPs over HTTP are confirmed malicious."},
    {"id":"R21","desc":"Many subdomains with suspicious keywords",
     "category":"url","conditions":["url_many_subdomains","url_suspicious_keywords"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":82,
     "rationale":"Attackers nest brand names as subdomains to deceive users."},
    {"id":"R22","desc":"Suspicious keywords combined with suspicious TLD",
     "category":"url","conditions":["url_suspicious_keywords","url_suspicious_tld"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":84,
     "rationale":"APWG: login/verify keywords appear in 78% of confirmed phishing URLs."},
    {"id":"R23","desc":"Typosquatting URL — digit replaces letter",
     "category":"url","conditions":["url_typosquatting","url_http"],
     "conclusion":"url_risk_critical","severity":"CRITICAL","confidence":93,
     "rationale":"Typosquatting is a primary phishing vector per ICANN abuse reports."},
    {"id":"R24","desc":"Very long URL with suspicious keywords",
     "category":"url","conditions":["url_very_long","url_suspicious_keywords"],
     "conclusion":"url_risk_medium","severity":"MEDIUM","confidence":68,
     "rationale":"Long URLs hide the true domain from users reading the address bar."},
    {"id":"R25","desc":"URL contains @ symbol — browser redirect trick",
     "category":"url","conditions":["url_has_at_symbol"],
     "conclusion":"url_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"RFC 3986: browsers treat everything before @ as credentials, going to post-@ domain."},
    {"id":"R26","desc":"URL shortener over HTTP",
     "category":"url","conditions":["url_shortener","url_http"],
     "conclusion":"url_risk_medium","severity":"MEDIUM","confidence":70,
     "rationale":"URL shorteners prevent destination verification; high misuse in phishing."},
    {"id":"R27","desc":"Suspicious TLD with suspicious keywords",
     "category":"url","conditions":["url_suspicious_tld","url_suspicious_keywords"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":80,
     "rationale":"SpamHaus: .tk .ml .ga TLDs account for 40%+ of phishing domains globally."},
    {"id":"R28","desc":"Hex-encoded URL with suspicious keywords",
     "category":"url","conditions":["url_hex_encoded","url_suspicious_keywords"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":83,
     "rationale":"Hex encoding (e.g. %70%61%79) is used to bypass URL-based phishing filters."},
    {"id":"R29","desc":"Bank mimicry domain over HTTP",
     "category":"url","conditions":["url_bank_mimicry","url_http"],
     "conclusion":"url_risk_critical","severity":"CRITICAL","confidence":94,
     "rationale":"Financial brand impersonation is the #1 phishing category per APWG Q3 2023."},
    {"id":"R30","desc":"HTTPS URL with standard domain — appears safe",
     "category":"url","conditions":["url_https","url_standard_domain"],
     "conclusion":"url_risk_low","severity":"LOW","confidence":80,
     "rationale":"HTTPS plus clean domain structure is the baseline for safe web navigation."},
    {"id":"R31","desc":"Redirect parameter with suspicious keywords",
     "category":"url","conditions":["url_redirect_param","url_suspicious_keywords"],
     "conclusion":"url_risk_high","severity":"HIGH","confidence":81,
     "rationale":"Open redirects allow phishers to use trusted domains to forward to malicious ones."},
    {"id":"R32","desc":"Unusual port with HTTP",
     "category":"url","conditions":["url_unusual_port","url_http"],
     "conclusion":"url_risk_medium","severity":"MEDIUM","confidence":67,
     "rationale":"Legitimate sites rarely serve on non-standard ports; often indicates malicious hosting."},
    {"id":"R33","desc":"IP address with suspicious keywords — high-confidence phishing",
     "category":"url","conditions":["url_has_ip","url_suspicious_keywords"],
     "conclusion":"url_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"Combination of IP plus phishing keywords has 95%+ precision in APWG dataset."},
    {"id":"R34","desc":"Typosquatting with suspicious keywords — definitive phishing",
     "category":"url","conditions":["url_typosquatting","url_suspicious_keywords"],
     "conclusion":"url_risk_critical","severity":"CRITICAL","confidence":96,
     "rationale":"Typosquatting plus phishing keywords is the highest-precision URL phishing signal."},

    # ══════════════════════════════════════════════════════
    # PHISHING DETECTION  R35–R50
    # ══════════════════════════════════════════════════════
    {"id":"R35","desc":"Urgent words with no link — social pressure only",
     "category":"phishing","conditions":["msg_urgent_words"],
     "conclusion":"phishing_risk_medium","severity":"MEDIUM","confidence":72,
     "rationale":"Urgency is a social engineering technique present in 65% of phishing messages."},
    {"id":"R36","desc":"Urgent message with embedded link",
     "category":"phishing","conditions":["msg_urgent_words","msg_has_link"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":85,
     "rationale":"FBI IC3: urgency plus link combination is the primary phishing delivery mechanism."},
    {"id":"R37","desc":"Request for personal information with urgency",
     "category":"phishing","conditions":["msg_asks_personal_info","msg_urgent_words"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":88,
     "rationale":"Legitimate organisations never request credentials via email per security policy."},
    {"id":"R38","desc":"Account threat with urgent wording",
     "category":"phishing","conditions":["msg_account_threat","msg_urgent_words"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":89,
     "rationale":"Account threat plus verification request is the #2 phishing lure per APWG."},
    {"id":"R39","desc":"Prize claim with embedded link",
     "category":"phishing","conditions":["msg_prize_claim","msg_has_link"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":87,
     "rationale":"Prize claims exploit greed bias; linking to malicious page is standard technique."},
    {"id":"R40","desc":"Bank impersonation with account threat",
     "category":"phishing","conditions":["msg_impersonates_bank","msg_account_threat"],
     "conclusion":"phishing_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"Bank impersonation plus account threat is the most reported phishing combination."},
    {"id":"R41","desc":"Poor grammar with urgent words",
     "category":"phishing","conditions":["msg_poor_grammar","msg_urgent_words"],
     "conclusion":"phishing_risk_medium","severity":"MEDIUM","confidence":67,
     "rationale":"Grammar errors plus urgency indicate offshore phishing operations."},
    {"id":"R42","desc":"Generic greeting with account threat",
     "category":"phishing","conditions":["msg_generic_greeting","msg_account_threat"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":82,
     "rationale":"Generic greetings indicate mass-targeted campaigns; legitimate contacts use names."},
    {"id":"R43","desc":"Legal threat with urgent words",
     "category":"phishing","conditions":["msg_legal_threat","msg_urgent_words"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":85,
     "rationale":"Fear-based social engineering; legal threats override rational judgment."},
    {"id":"R44","desc":"Link with penalty words — click to avoid punishment",
     "category":"phishing","conditions":["msg_has_link","msg_penalty_words"],
     "conclusion":"phishing_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"Penalty plus link combination has highest click-through rate in phishing simulations."},
    {"id":"R45","desc":"Government impersonation with account threat",
     "category":"phishing","conditions":["msg_impersonates_govt","msg_account_threat"],
     "conclusion":"phishing_risk_critical","severity":"CRITICAL","confidence":93,
     "rationale":"Government impersonation exploits authority bias; heavily reported in Pakistan."},
    {"id":"R46","desc":"Sender mismatch with urgent words",
     "category":"phishing","conditions":["msg_sender_mismatch","msg_urgent_words"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":86,
     "rationale":"Email spoofing plus urgency is a classic combined phishing signal."},
    {"id":"R47","desc":"Disaster hook with embedded link",
     "category":"phishing","conditions":["msg_disaster_hook","msg_has_link"],
     "conclusion":"phishing_risk_high","severity":"HIGH","confidence":80,
     "rationale":"Crisis-themed phishing spikes during real disasters; exploits empathy."},
    {"id":"R48","desc":"OTP request with account threat",
     "category":"phishing","conditions":["msg_asks_otp","msg_account_threat"],
     "conclusion":"phishing_risk_critical","severity":"CRITICAL","confidence":97,
     "rationale":"OTP requests via message are NEVER legitimate; classic SIM-swap precursor."},
    {"id":"R49","desc":"OTP or password request alone",
     "category":"phishing","conditions":["msg_asks_otp"],
     "conclusion":"phishing_risk_critical","severity":"CRITICAL","confidence":94,
     "rationale":"Any OTP request through a message channel is a definitive phishing signal."},
    {"id":"R50","desc":"Message appears legitimate — no phishing indicators",
     "category":"phishing","conditions":["msg_no_red_flags"],
     "conclusion":"phishing_risk_low","severity":"LOW","confidence":75,
     "rationale":"Absence of all phishing indicators yields correctly low risk classification."},

    # ══════════════════════════════════════════════════════
    # SCAM DETECTION  R51–R66
    # ══════════════════════════════════════════════════════
    {"id":"R51","desc":"Unrealistic reward with time pressure",
     "category":"scam","conditions":["scam_unrealistic_reward","scam_time_pressure"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"FTC: unrealistic offer plus deadline is the #1 financial scam combination."},
    {"id":"R52","desc":"Advance fee with time pressure",
     "category":"scam","conditions":["scam_advance_fee","scam_time_pressure"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":96,
     "rationale":"Advance fee fraud (419 scam): time pressure forces victims to pay quickly."},
    {"id":"R53","desc":"Unsolicited win with advance fee",
     "category":"scam","conditions":["scam_unsolicited_win","scam_advance_fee"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":97,
     "rationale":"Winning a contest you never entered plus fee request is definitively fraudulent."},
    {"id":"R54","desc":"Unrealistic reward alone",
     "category":"scam","conditions":["scam_unrealistic_reward"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":90,
     "rationale":"FTC: too-good-to-be-true offers are the #1 financial scam indicator."},
    {"id":"R55","desc":"Advance fee request alone",
     "category":"scam","conditions":["scam_advance_fee"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":93,
     "rationale":"Advance fee fraud — victim pays fees for a non-existent reward."},
    {"id":"R56","desc":"Unsolicited prize claim alone",
     "category":"scam","conditions":["scam_unsolicited_win"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"Unsolicited prize claims are definitionally fraudulent per FTC guidelines."},
    {"id":"R57","desc":"Time pressure with easy money job",
     "category":"scam","conditions":["scam_time_pressure","scam_easy_money_job"],
     "conclusion":"scam_risk_high","severity":"HIGH","confidence":85,
     "rationale":"Time pressure on easy income offer is the textbook money mule recruitment tactic."},
    {"id":"R58","desc":"Gift card payment with time pressure",
     "category":"scam","conditions":["scam_gift_card_payment","scam_time_pressure"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":98,
     "rationale":"Gift card payment plus urgency — 100% of legitimate entities reject this method."},
    {"id":"R59","desc":"Gift card payment request alone",
     "category":"scam","conditions":["scam_gift_card_payment"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"Gift card/crypto payment requests are untraceable and exclusively used by scammers."},
    {"id":"R60","desc":"Nigerian prince or 419 pattern",
     "category":"scam","conditions":["scam_419_pattern"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":97,
     "rationale":"419 advance fee fraud — documented by INTERPOL; highly recognisable pattern."},
    {"id":"R61","desc":"Investment fraud with unrealistic reward",
     "category":"scam","conditions":["scam_investment_fraud","scam_unrealistic_reward"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":97,
     "rationale":"Guaranteed high returns plus unrealistic amounts is definitive Ponzi scheme pattern."},
    {"id":"R62","desc":"Investment fraud alone",
     "category":"scam","conditions":["scam_investment_fraud"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"Guaranteed returns are illegal to promise; hallmark of Ponzi/pyramid schemes."},
    {"id":"R63","desc":"Tech support scam with time pressure",
     "category":"scam","conditions":["scam_tech_support","scam_time_pressure"],
     "conclusion":"scam_risk_high","severity":"HIGH","confidence":90,
     "rationale":"Tech support scams cost victims $924M annually per FBI IC3 2022 report."},
    {"id":"R64","desc":"Tech support scam alone",
     "category":"scam","conditions":["scam_tech_support"],
     "conclusion":"scam_risk_high","severity":"HIGH","confidence":85,
     "rationale":"Remote access requests from unsolicited tech support are fraudulent."},
    {"id":"R65","desc":"Wire transfer with time pressure",
     "category":"scam","conditions":["scam_wire_transfer","scam_time_pressure"],
     "conclusion":"scam_risk_critical","severity":"CRITICAL","confidence":94,
     "rationale":"Wire transfer plus urgency is the primary BEC (Business Email Compromise) attack."},
    {"id":"R66","desc":"Message has no scam indicators",
     "category":"scam","conditions":["scam_no_indicators"],
     "conclusion":"scam_risk_low","severity":"LOW","confidence":70,
     "rationale":"Absence of all scam indicators; system correctly classifies as low-risk."},

    # ══════════════════════════════════════════════════════
    # CYBER HYGIENE  R67–R80
    # ══════════════════════════════════════════════════════
    {"id":"R67","desc":"Password reuse across multiple accounts",
     "category":"hygiene","conditions":["hygiene_password_reuse"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":85,
     "rationale":"CIS Control 5: credential stuffing attacks rely entirely on password reuse."},
    {"id":"R68","desc":"No two-factor authentication enabled",
     "category":"hygiene","conditions":["hygiene_no_2fa"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":83,
     "rationale":"Microsoft: 99.9% of account compromises prevented by enabling MFA."},
    {"id":"R69","desc":"Public Wi-Fi without VPN",
     "category":"hygiene","conditions":["hygiene_public_wifi"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":80,
     "rationale":"Public Wi-Fi enables MITM attacks; VPN encrypts traffic per NIST guidance."},
    {"id":"R70","desc":"No software updates — unpatched vulnerabilities",
     "category":"hygiene","conditions":["hygiene_no_updates"],
     "conclusion":"hygiene_risk_medium","severity":"MEDIUM","confidence":75,
     "rationale":"60% of breaches exploit known vulnerabilities with available patches (Ponemon 2022)."},
    {"id":"R71","desc":"No antivirus or security software",
     "category":"hygiene","conditions":["hygiene_no_antivirus"],
     "conclusion":"hygiene_risk_medium","severity":"MEDIUM","confidence":78,
     "rationale":"CIS Control 10: antimalware software is a foundational security control."},
    {"id":"R72","desc":"Opens email attachments from unknown senders",
     "category":"hygiene","conditions":["hygiene_opens_attachments"],
     "conclusion":"hygiene_risk_critical","severity":"CRITICAL","confidence":91,
     "rationale":"91% of cyberattacks begin with a phishing email; opening attachments is primary vector."},
    {"id":"R73","desc":"Shares passwords with others",
     "category":"hygiene","conditions":["hygiene_shares_passwords"],
     "conclusion":"hygiene_risk_critical","severity":"CRITICAL","confidence":90,
     "rationale":"Password sharing violates need-to-know principle; insider threat vector per SANS."},
    {"id":"R74","desc":"Password reuse combined with no 2FA",
     "category":"hygiene","conditions":["hygiene_password_reuse","hygiene_no_2fa"],
     "conclusion":"hygiene_risk_critical","severity":"CRITICAL","confidence":93,
     "rationale":"Reuse plus no MFA means single credential breach compromises all accounts."},
    {"id":"R75","desc":"Public Wi-Fi combined with no antivirus",
     "category":"hygiene","conditions":["hygiene_public_wifi","hygiene_no_antivirus"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":87,
     "rationale":"MITM attack on public WiFi can deliver malware; no AV means no detection."},
    {"id":"R76","desc":"Opens attachments combined with no antivirus",
     "category":"hygiene","conditions":["hygiene_opens_attachments","hygiene_no_antivirus"],
     "conclusion":"hygiene_risk_critical","severity":"CRITICAL","confidence":94,
     "rationale":"Opening unknown attachments without AV is the highest-risk hygiene combination."},
    {"id":"R77","desc":"Shares passwords combined with password reuse",
     "category":"hygiene","conditions":["hygiene_shares_passwords","hygiene_password_reuse"],
     "conclusion":"hygiene_risk_critical","severity":"CRITICAL","confidence":95,
     "rationale":"Sharing reused passwords exposes all accounts through a single social interaction."},
    {"id":"R78","desc":"No updates combined with no antivirus",
     "category":"hygiene","conditions":["hygiene_no_updates","hygiene_no_antivirus"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":86,
     "rationale":"Unpatched system without AV has no defence against known malware exploits."},
    {"id":"R79","desc":"No 2FA combined with public Wi-Fi",
     "category":"hygiene","conditions":["hygiene_no_2fa","hygiene_public_wifi"],
     "conclusion":"hygiene_risk_high","severity":"HIGH","confidence":84,
     "rationale":"Credential interception on public Wi-Fi without MFA allows immediate account takeover."},
    {"id":"R80","desc":"All cyber hygiene practices are good",
     "category":"hygiene","conditions":["hygiene_good_practices"],
     "conclusion":"hygiene_risk_low","severity":"LOW","confidence":82,
     "rationale":"All CIS Controls baseline hygiene practices met; low residual risk."},
]

# ============================================================
# CONSTANTS — Used by inference_engine.py
# ============================================================
COMMON_PASSWORDS = [
    'password','123456','12345678','qwerty','abc123','monkey','1234567',
    'letmein','trustno1','dragon','baseball','iloveyou','master','sunshine',
    'ashley','bailey','passw0rd','shadow','123123','654321','superman',
    'qazwsx','michael','football','password1','welcome','admin','login',
    'hello','pass','test','root','user','guest','changeme'
]
SUSPICIOUS_URL_KEYWORDS = [
    'login','verify','secure','account','update','confirm','banking',
    'paypal','ebay','amazon','apple','microsoft','support','helpdesk',
    'reset','password','signin','signup','webscr','cmd'
]
URL_SHORTENERS = [
    'bit.ly','tinyurl.com','t.co','goo.gl','ow.ly','buff.ly',
    'short.link','rb.gy','cutt.ly','is.gd'
]
SUSPICIOUS_TLDS = ['.xyz','.tk','.ml','.ga','.cf','.gq','.pw','.cc']
BANK_MIMICRY_KEYWORDS = [
    'paypal','paypai','pay-pal','bank','citibank','wells-fargo','chase',
    'hsbc','barclays','easypaisa','jazzcash','hbl','meezan','alfalah'
]
URGENT_WORDS = [
    'urgent','immediately','asap','right now','act now','limited time',
    'expires','final notice','last chance','warning','alert','critical'
]
PENALTY_WORDS = [
    'suspended','disabled','terminated','blocked','locked','restricted',
    'penalty','fine','deactivated'
]
PRIZE_WORDS = [
    'winner','won','prize','lottery','reward','jackpot','congratulations',
    'selected','lucky','free gift','cash prize','gift card'
]
SCAM_ADVANCE_FEE_WORDS = [
    'advance fee','processing fee','transfer fee','release fee',
    'handling charge','upfront payment','small fee','insurance fee'
]
SCAM_INVESTMENT_WORDS = [
    'guaranteed return','100% profit','double your money','risk free',
    'high returns','passive income','crypto investment',
    'binary options','forex guaranteed'
]
