# ============================================================
# test_scenarios.py – CyberGuard Advisor
# 14 predefined test cases validating all 5 domains.
# ============================================================

TEST_SCENARIOS = [
    {"id":"T01","name":"Common Dictionary Password","domain":"password","input_type":"password",
     "input":{"password":"123456","username":""},
     "description":"Tests detection of most common dictionary password.",
     "expected_severity":"CRITICAL","expected_rules":["R06","R17"],
     "rationale":"R06: common_password in NIST blacklist. R17: common+digits combo."},
    {"id":"T02","name":"Strong Password","domain":"password","input_type":"password",
     "input":{"password":"P@ssw0rd!XY99#","username":""},
     "description":"Tests that a strong complex password scores LOW/SAFE.",
     "expected_severity":"SAFE","expected_rules":["R12","R13"],
     "rationale":"R12/R13 fires: length>12, has uppercase, digit, special char."},
    {"id":"T03","name":"Password Contains Username","domain":"password","input_type":"password",
     "input":{"password":"alice2024","username":"alice"},
     "description":"Tests detection of username embedded in password.",
     "expected_severity":"HIGH","expected_rules":["R08"],
     "rationale":"R08: contains_username=TRUE fires HIGH severity."},
    {"id":"T04","name":"Keyboard Pattern Password","domain":"password","input_type":"password",
     "input":{"password":"qwerty","username":""},
     "description":"Tests detection of keyboard walking pattern.",
     "expected_severity":"CRITICAL","expected_rules":["R14","R18"],
     "rationale":"R14: keyboard_pattern fires. R18: keyboard+sequential combination."},
    {"id":"T05","name":"Safe HTTPS URL","domain":"url","input_type":"url",
     "input":{"url":"https://www.google.com"},
     "description":"Tests that a legitimate HTTPS URL scores SAFE.",
     "expected_severity":"SAFE","expected_rules":["R30"],
     "rationale":"R30: https+standard_domain fires LOW. No threat rules fire."},
    {"id":"T06","name":"Typosquatting URL","domain":"url","input_type":"url",
     "input":{"url":"http://paypa1-login.xyz/verify"},
     "description":"Tests typosquatting with digit substitution.",
     "expected_severity":"CRITICAL","expected_rules":["R23","R27"],
     "rationale":"R23: url_typosquatting CRITICAL. R27: suspicious TLD .xyz HIGH."},
    {"id":"T07","name":"IP Address URL","domain":"url","input_type":"url",
     "input":{"url":"http://192.168.1.1/paypal/login"},
     "description":"Tests detection of IP address masking real domain.",
     "expected_severity":"CRITICAL","expected_rules":["R20","R33"],
     "rationale":"R33: ip+suspicious_keywords CRITICAL. R20: ip+http HIGH."},
    {"id":"T08","name":"URL with @ Symbol","domain":"url","input_type":"url",
     "input":{"url":"http://trusted.com@evil.com/path"},
     "description":"Tests @ symbol trick that redirects to attacker domain.",
     "expected_severity":"CRITICAL","expected_rules":["R25"],
     "rationale":"R25: url_has_at_symbol fires CRITICAL (RFC 3986 browser redirect)."},
    {"id":"T09","name":"OTP Phishing Message","domain":"phishing","input_type":"message",
     "input":{"message":"Dear Customer, Your account has been suspended. Please verify your OTP immediately to avoid account closure. Click: http://bit.ly/verify"},
     "description":"Tests OTP request combined with account threat.",
     "expected_severity":"CRITICAL","expected_rules":["R44","R49","R36"],
     "rationale":"R47: asks_otp=CRITICAL (96%). R37: account_threat. R43: link+penalty."},
    {"id":"T10","name":"Nigerian Prince Scam","domain":"scam","input_type":"message",
     "input":{"message":"Dear Friend, I am Prince Emmanuel of Nigeria. I have 45 million dollars to transfer. Please send advance fee of 500 dollars via Western Union."},
     "description":"Tests classic 419 advance-fee scam.",
     "expected_severity":"CRITICAL","expected_rules":["R55","R50"],
     "rationale":"R55: 419_pattern CRITICAL (97%). R50: advance_fee CRITICAL (95%)."},
    {"id":"T11","name":"Safe Legitimate Message","domain":"phishing","input_type":"message",
     "input":{"message":"Hi John, the meeting is confirmed for Monday at 10 AM. Please review the attached agenda. Best regards, Sarah."},
     "description":"Tests that normal message produces no false positives.",
     "expected_severity":"SAFE","expected_rules":["R50","R66"],
     "rationale":"R48/R62: no_red_flags and no_indicators fire LOW. No phishing rules fire."},
    {"id":"T12","name":"Investment Fraud Message","domain":"scam","input_type":"message",
     "input":{"message":"Earn 100% profit guaranteed! Double your money in 7 days with our crypto investment. Risk free, respond within 24 hours!"},
     "description":"Tests investment fraud with guaranteed returns.",
     "expected_severity":"CRITICAL","expected_rules":["R62","R50"],
     "rationale":"R56: investment_fraud CRITICAL. R61: investment+unrealistic combo. R49: unrealistic_reward."},
    {"id":"T13","name":"Poor Cyber Hygiene","domain":"hygiene","input_type":"hygiene",
     "input":{"password_reuse":True,"no_2fa":True,"public_wifi":True,"no_updates":False,"no_antivirus":False,"opens_attachments":True,"shares_passwords":False},
     "description":"Tests detection of multiple poor hygiene practices.",
     "expected_severity":"CRITICAL","expected_rules":["R68","R70","R63"],
     "rationale":"R68: opens_attachments CRITICAL. R70: reuse+no2fa compound CRITICAL."},
    {"id":"T14","name":"Good Cyber Hygiene","domain":"hygiene","input_type":"hygiene",
     "input":{"password_reuse":False,"no_2fa":False,"public_wifi":False,"no_updates":False,"no_antivirus":False,"opens_attachments":False,"shares_passwords":False},
     "description":"Tests that good practices result in SAFE rating.",
     "expected_severity":"SAFE","expected_rules":["R80"],
     "rationale":"R72: hygiene_good_practices fires LOW. All bad hygiene rules absent."},
    # ── ADDITIONAL SCENARIOS T15-T20 ──────────────────────
    {"id":"T15","name":"Bank Impersonation Phishing",
     "domain":"phishing","input_type":"message",
     "input":{"message":"Your HBL account has been flagged. Verify immediately at http://hb1-secure.xyz/login or your account will be deactivated."},
     "description":"Tests bank impersonation combined with account threat.",
     "expected_severity":"CRITICAL","expected_rules":["R40","R44","R38"],
     "rationale":"R40: bank impersonation+account_threat CRITICAL. R44: link+penalty CRITICAL."},
    {"id":"T16","name":"Government Impersonation",
     "domain":"phishing","input_type":"message",
     "input":{"message":"FBR Notice: Your tax return is overdue. Failure to respond within 24 hours will result in a fine. Click here to file: http://fbr-pk.xyz"},
     "description":"Tests government agency impersonation with legal threat.",
     "expected_severity":"CRITICAL","expected_rules":["R44","R43"],
     "rationale":"R45: govt+account_threat CRITICAL. R43: legal_threat+urgent CRITICAL."},
    {"id":"T17","name":"Gift Card Scam with Urgency",
     "domain":"scam","input_type":"message",
     "input":{"message":"URGENT: You owe Rs 5000 in unpaid fees. Pay immediately using Easypaisa or Google Play gift card. Last chance before account suspension."},
     "description":"Tests gift card payment demand with time pressure.",
     "expected_severity":"CRITICAL","expected_rules":["R58","R59"],
     "rationale":"R58: gift_card+time_pressure CRITICAL (98%). R59: gift_card alone CRITICAL."},
    {"id":"T18","name":"Medium Strength URL",
     "domain":"url","input_type":"url",
     "input":{"url":"http://bit.ly/special-offer-login"},
     "description":"Tests URL shortener over HTTP with suspicious keywords.",
     "expected_severity":"MEDIUM","expected_rules":["R26","R19"],
     "rationale":"R26: shortener+http MEDIUM. R19: http+suspicious_keywords HIGH."},
    {"id":"T19","name":"Romance Fraud Message",
     "domain":"scam","input_type":"message",
     "input":{"message":"My darling, I am stuck in Dubai airport. I lost my wallet. Please send 500 dollars via Western Union and I will repay double when I return my love."},
     "description":"Tests romance fraud pattern with wire transfer request.",
     "expected_severity":"CRITICAL","expected_rules":["R59","R55"],
     "rationale":"R65: wire_transfer+time_pressure CRITICAL. R55: advance_fee CRITICAL."},
    {"id":"T20","name":"Hex Encoded Phishing URL",
     "domain":"url","input_type":"url",
     "input":{"url":"http://192.168.1.1/%70%61%79%70%61%6C/login/verify"},
     "description":"Tests IP address with hex encoding and phishing keywords.",
     "expected_severity":"CRITICAL","expected_rules":["R33","R28"],
     "rationale":"R33: ip+suspicious_keywords CRITICAL. R28: hex+suspicious_keywords HIGH."},
]
